# Generated by Django 3.1.1 on 2020-10-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=15, verbose_name='ruc')),
            ],
            options={
                'verbose_name': 'Información de entidad',
                'verbose_name_plural': 'Información de entidades',
            },
        ),
    ]
