# Generated by Django 3.1.1 on 2020-10-17 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Título')),
                ('benefits', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Producto financiero',
            },
        ),
        migrations.CreateModel(
            name='Petitioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, verbose_name='Ruc')),
                ('document_number', models.CharField(max_length=8, verbose_name='Número de documento')),
                ('document_type', models.CharField(choices=[('1', 'DNI')], default='1', max_length=1, verbose_name='Tipo de documento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=31, verbose_name='Teléfono/Celular')),
                ('internal_client', models.BooleanField(default=False, verbose_name='¿Ya es cliente?')),
            ],
            options={
                'verbose_name': 'Solicitante',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            options={
                'verbose_name': 'Propósito',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30, unique=True, verbose_name='Alias')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('required', models.BooleanField(default=False, verbose_name='¿Es obligatorio?')),
            ],
            options={
                'verbose_name': 'Requisito',
            },
        ),
        migrations.CreateModel(
            name='RequestedFinantialProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Consultado'), ('2', 'Pre-aprobado'), ('0', 'Rechazado')], default='1', max_length=1, verbose_name='Status')),
                ('annual_income', models.PositiveIntegerField(blank=True, null=True)),
                ('infocorp_debt', models.PositiveIntegerField(blank=True, null=True)),
                ('financial_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_sources.financialproduct')),
                ('petitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_sources.petitioner')),
                ('purpose_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_sources.purpose')),
            ],
            options={
                'verbose_name': 'Solicitud de Producto',
            },
        ),
    ]
