# Generated by Django 3.1.1 on 2020-10-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_sources', '0003_financialproduct_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualIncomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'Facturación anual',
                'verbose_name_plural': 'Facturaciones anuales',
            },
        ),
        migrations.CreateModel(
            name='InfocorpDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'Deuda Infocorp',
                'verbose_name_plural': 'Deudas Infocorp',
            },
        ),
        migrations.RemoveField(
            model_name='petitioner',
            name='internal_client',
        ),
        migrations.AddField(
            model_name='petitioner',
            name='completed_register',
            field=models.BooleanField(default=False, verbose_name='Registro completo'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='requestedfinantialproduct',
            name='annual_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_sources.annualincomes'),
        ),
        migrations.AlterField(
            model_name='requestedfinantialproduct',
            name='infocorp_debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_sources.infocorpdebt'),
        ),
    ]
