# Generated by Django 3.1.1 on 2020-10-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_sources', '0004_auto_20201017_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purpose',
            old_name='name',
            new_name='text',
        ),
    ]
