# Generated by Django 3.1.1 on 2020-10-17 20:13

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info_sources', '0005_auto_20201017_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityinformation',
            name='data',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AddField(
            model_name='entityinformation',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='entityinformation',
            name='source',
            field=models.CharField(blank=True, choices=[('1', 'Sunat'), ('2', 'Osce'), ('0', 'Otra')], max_length=2, verbose_name='Fuente'),
        ),
        migrations.AddField(
            model_name='entityinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
