# Generated by Django 3.1.1 on 2020-10-18 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_sources', '0006_auto_20201017_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityinformation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entityinformation',
            name='updated_at',
        ),
    ]
