# Generated by Django 3.1.1 on 2020-10-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_sources', '0007_auto_20201018_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialproduct',
            options={'verbose_name': 'Producto financiero', 'verbose_name_plural': 'Productos financieros'},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name': 'Propósito de préstamo', 'verbose_name_plural': 'Propósitos de préstamo'},
        ),
        migrations.AlterModelOptions(
            name='requestedfinantialproduct',
            options={'verbose_name': 'Solicitud de Producto', 'verbose_name_plural': 'Solicitudes de Producto'},
        ),
        migrations.AlterField(
            model_name='requestedfinantialproduct',
            name='annual_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_sources.annualincomes', verbose_name='Facturación anual'),
        ),
        migrations.AlterField(
            model_name='requestedfinantialproduct',
            name='financial_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_sources.financialproduct', verbose_name='Producto financiero'),
        ),
        migrations.AlterField(
            model_name='requestedfinantialproduct',
            name='infocorp_debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_sources.infocorpdebt', verbose_name='Deuda Infocorp'),
        ),
        migrations.AlterField(
            model_name='requestedfinantialproduct',
            name='petitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_sources.petitioner', verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='requestedfinantialproduct',
            name='purpose_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_sources.purpose', verbose_name='Propósito de préstamo'),
        ),
    ]
